### PR TITLE
add armed night

### PR DESCRIPTION
**Pull request by Aidenkwok**
map partset_b on HKC to arm_night on HA

### CODE REVIEW

**Comment by Aidenkwok** [comment]
> ```python
> _attr_supported_features = (
> ```

added 👍

**Comment by jasonmadigan** [comment]
thanks @Aidenkwok!

**Comment by jasonmadigan** [comment]
I'll create a pre-release at the weekend to test.

**Comment by jasonmadigan** [comment]
@Aidenkwok https://github.com/jasonmadigan/ha-hkc/releases/tag/1.0.17-rc2  - can check it out via "beta" releases in HACS. My partset B is set to "panic", but it does seem to work. You might give it a spin too. If happy, will push final.

**Comment by Aidenkwok** [comment]
@jasonmadigan can confirm its working for me too!

**Comment by jasonmadigan** [comment]
excellent, thanks for the contrib @Aidenkwok

**Pull request merged**
